development:
  admin_username: test
  admin_password: test

test:
  admin_username: test
  admin_password: test

production:
  admin_username: <%= ENV["ADMIN_USERNAME"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
